title: "~/kh"
author: "Kyle Huggins"
description: >- # this means to ignore newlines until "baseurl:"
  Kyle Huggins' home directory on TAZ.
baseurl: "/~khuggins/site/"
url: "http://taz.harding.edu"

github_username: kjhx

# Build settings
exclude: ["Makefile", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
plugins:
  - jekyll-gist
  - jekyll-minifier

permalink: /:categories/:title.html

sass:
  style: compressed
