title: "~/kh"
author: "Kyle Huggins"
description: >- # this means to ignore newlines until "baseurl:"
  Kyle Huggins' home directory on TAZ.
baseurl: "/~khuggins/site/"
url: "http://taz.harding.edu"

github_username: kjhx

# Build settings
markdown: kramdown
plugins:
  - jekyll-gist
permalink: /:categories/:title.html
