title: "Kyle Huggins - TAZ"
author: "Kyle Huggins"
description: >- # this means to ignore newlines until "baseurl:"
  Kyle Huggins' home directory on TAZ.
baseurl: ""
url: ""

github_username: kjhx

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: /:categories/:title.html
